services:
  - type: web
    name: ghana-card-backend
    env: python
    plan: free
    buildCommand: pip install -r f2/requirements.txt
    startCommand: gunicorn app:app
    rootDir: f2
    envVars:
      - key: PYTHON_VERSION
        value: 3.10