services:
  - type: web
    name: orbitend-backend
    env: docker
    plan: free
    dockerfilePath: f2/Dockerfile
    rootDir: f2
    envVars:
      - key: PORT
        value: 10000
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
