services:
  - type: web
    name: ghana-card-backend
    env: python
    plan: free
    rootDir: f2
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
