export const Catalog = [
    {
      cat: "Home",
      image: "../pic/home.jpg",
      skills: [
        "General Handyman",
        "Carpentry (repairs, installations)",
        "Plumbing (household)",
        "Electrical (household)",
        "Painting (interior/ exterior)",
        "Appliance Repair",
        "HVAC (heating, ventilation, air conditioning)",
        "Cleaning (house)",
        "Landscaping / Gardening",
        "Pest Control",
        "Locksmith (residential)",
        "Window and Door Installation / Repair",
        "Flooring Installation",
        "Interior Decorating",
        "Furniture Repair / Restoration",
      ],
    },
    {
      cat: "Electric",
      image: "../pic/electric.jpg",
      skills: [
        "Electrical Wiring (residential, commercial)",
        "Appliance Repair (electrical)",
        "Electronics Repair",
        "Low Voltage Systems (security, data)",
        "Solar Panel Installation",
        "Wind Turbine Maintenance",
        "Generator Service",
        "Lighting Installation/Design",
      ],
    },
    {
      cat: "Wood",
      image: "../pic/wood.jpg",
      skills: [
        "Cabinet Making",
        "Furniture Making (custom, repair)",
        "Woodworking (general, carving, turning)",
        "Framing Carpentry",
        "Finish Carpentry",
        "Luthier (instrument making/repair)",
        "Wood Carving",
        "Wood Turning",
        "Boat Building (wooden)",
        "Timber Framing",
        "Parquet Flooring",
        "Wooden Toy Making",
      ],
    },
    {
      cat: "Vehicle",
      image: "../pic/vehicle.jpg",
      skills: [
        "Auto Mechanics (general repair)",
        "Auto Body Repair",
        "Automotive Electrical",
        "Tire Services",
        "Transmission Repair",
        "Brake Service",
        "Auto Detailing",
        "Motorcycle Mechanics",
        "Boat Mechanics",
        "Aircraft Mechanics",
        "Heavy Equipment Mechanics",
        "Vehicle Upholstery",
      ],
    },
    {
      cat: "Beauty",
      image: "../pic/beauty.jpg",
      skills: [
        "Hairdressing / Styling",
        "Barbering",
        "Makeup Artistry",
        "Nail Care (manicures, pedicures)",
        "Esthetics (skincare)",
        "Massage Therapy",
        "Cosmetology (multiple services)",
        "Lash/Brow Services",
        "Tattoo Artistry (cosmetic/artistic)",
        "Permanent Makeup",
      ],
    },
    {
      cat: "Metal",
      image: "../pic/metal.jpg",
      skills: [
        "Welding",
        "Metal Fabrication",
        "Blacksmithing",
        "Machining",
        "Locksmith (metal systems)",
        "Automotive Body Repair",
        "Jewelry Making (metal)",
        "Metal Sculpting",
        "Farrier (horseshoes)",
        "Metal Engraving",
        "Ornamental Ironwork",
        "Knife Making",
      ],
    },
    {
      cat: "Construction",
      image: "../pic/Construction.jpg",
      skills: [
        "General Contracting",
        "Carpentry (framing, roofing, finishing)",
        "Masonry (brick, block, stone)",
        "Roofing",
        "Plumbing (construction)",
        "Electrical (construction)",
        "HVAC Installation",
        "Drywall Installation",
        "Painting (construction)",
        "Tile Setting",
        "Concrete Finishing",
        "Landscaping (site prep)",
        "Heavy Equipment Operation",
        "Excavation",
      ],
    },
    {
      cat: "Water",
      image: "../pic/water.jpg",
      skills: [
        "Plumbing (water systems)",
        "Irrigation System Installation/Repair",
        "Water Well Drilling",
        "Water Treatment",
        "Pool/Spa Service (maintenance, repair)",
        "Waterproofing",
        "Marine Mechanics (water systems)",
        "Hydraulic System Repair",
      ],
    },
    {
      cat: "Textiles & Leather",
      image: "../pic/textiles.jpg",
      skills: [
        "Sewing/Tailoring",
        "Leatherworking (bags, belts, shoes)",
        "Weaving",
        "Knitting",
        "Crocheting",
        "Upholstery (furniture)",
        "Shoemaking/Cobbling",
        "Textile Design",
        "Quilting",
        "Dressmaking",
        "Costume Design",
        "Millinery (hat making)",
      ],
    },
    {
      cat: "Ceramics & Pottery",
      image: "../pic/ceramic.jpg",
      skills: [
        "Pottery (wheel throwing)",
        "Pottery (hand-building)",
        "Ceramic Art (sculpture)",
        "Tile Making",
        "Ceramic Painting",
        "Kiln Operation",
        "Ceramic Art Restoration",
      ],
    },
    {
      cat: "Jewelry & Metalcraft",
      image: "../pic/jewelry.jpg",
      skills: [
        "Jewelry Design",
        "Jewelry Making",
        "Jewelry Repair",
        "Goldsmithing",
        "Silversmithing",
        "Metal Sculpting (small scale)",
        "Beadwork",
        "Lapidary (stone cutting)",
        "Watch / Clock Making/Repair",
        "Engraving (jewelry/metal)",
      ],
    },
    {
      cat: "Fine Arts",
      image: "../pic/fineArt.jpg",
      skills: [
        "Painting",
        "Sculpting",
        "Illustration",
        "Photography (fine art)",
        "Calligraphy",
        "Printmaking",
        "Digital Painting",
        "Mixed Media Art",
        "Drawing",
      ],
    },
    {
      cat: "Culinary Arts",
      image: "../pic/culinary.jpg",
      skills: [
        "Baking",
        "Cake Decorating",
        "Chef Services (specialized)",
        "Catering",
        "Chocolatier",
        "Confectionery",
        "Butchery (artisanal)",
        "Cheese Making (artisanal)",
        "Brewing (craft beer)",
        "Winemaking (small batch)",
        "Food Preservation",
      ],
    },
    {
      cat: "Technology & Electronics",
      image: "../pic/tech.jpg",
      skills: [
        "Computer Repair",
        "Electronics Repair (devices)",
        "Custom Electronics Design",
        "Audio / Visual Installation",
        "Network Troubleshooting",
        "Embedded Systems Development",
        "Robotics Servicing",
        "Drone Repair/Customization",
      ],
    },
    {
      cat: "Printing & Graphics",
      image: "../pic/printing.jpeg",
      skills: [
        "Graphic Design",
        "Screen Printing",
        "Sign Making",
        "Digital Printing",
        "Bookbinding",
        "Letterpress Printing",
        "Illustration (for print)",
        "Typesetting",
      ],
    },
    {
      cat: "Glasswork",
      image: "../pic/glass.jpeg",
      skills: [
        "Stained Glass Art",
        "Glass Blowing",
        "Glass Etching",
        "Glass Fusing",
        "Glass Sculpting",
        "Glass Repair / Restoration",
        "Mirror Making",
      ],
    },
    {
      cat: "Music & Instruments",
      image: "../pic/music.jpeg",
      skills: [
        "Instrument Repair (general)",
        "Luthier (stringed instruments)",
        "Piano Tuning",
        "Organ Building / Repair",
        "Brass / Woodwind Repair",
        "Custom Instrument Making",
        "Music Teaching (instrumental)",
      ],
    },
    {
      cat: "Event Services",
      image: "../pic/event.jpeg",
      skills: [
        "Event Planning",
        "Event Decorating",
        "Set Design",
        "Event Lighting",
        "Event Sound",
        "Event Catering",
        "Floral Arrangements (events)",
        "Party Rentals (specialized)",
      ],
    },
    {
      cat: "Pet Services",
      image: "../pic/pet.jpeg",
      skills: [
        "Pet Grooming",
        "Pet Training",
        "Pet Sitting / Walking (specialized)",
        "Custom Pet Accessories (making)",
        "Pet Photography",
        "Animal Massage Therapy",
      ],
    },
    {
      cat: "Renewable Energy",
      image: "../pic/renewable.jpeg", 
      skills: [
        "Solar Panel Installation",
        "Solar Panel Maintenance",
        "Wind Turbine Maintenance",
        "Renewable Energy System Design",
        "Energy Auditing (renewable focus)",
        "Small-Scale Hydro Installation",
      ],
    },
    {
      cat: "Education & Training",
      image: "../pic/education.jpeg",
      skills: [
        "Artisan Skill Instruction (specific craft)",
        "Vocational Training (skilled trades)",
        "Craft Mentoring",
        "Workshop Leading",
      ],
    },
    {
      cat: "Upcycling & Recycling",
      image: "../pic/recycling.jpeg",
      skills: [
        "Furniture Restoration (upcycling focus)",
        "Upcycled Clothing Design",
        "Art from Recycled Materials",
        "Product Life Extension / Repair",
        "Reclaimed Material Product Creation",
      ],
    },
    {
      cat: "Stone & Masonry Art",
      image: "../pic/stoneMasonary.jpeg",
      skills: [
        "Stone Carving",
        "Monument Creation",
        "Stone Sculpting",
        "Decorative Stone Masonry",
        "Artistic Paving Stone Installation",
      ],
    },
    {
      cat: "Digital Arts",
      image: "../pic/DigitalArts.jpeg",
      skills: [
        "Digital Painting",
        "3D Modeling",
        "Animation (2D/3D)",
        "Motion Graphics",
        "Web Design (artistic focus)",
        "Game Art",
        "Digital Sculpting",
        "Texture Art",
      ],
    },
];

let paymentCount = 0;

const updatePaymentCount = (newValue) => {
  paymentCount = newValue;
};

const getPaymentCount = () => paymentCount;

export {updatePaymentCount, getPaymentCount };